# Generated by Django 4.1.7 on 2023-02-24 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stories',
            new_name='Article',
        ),
    ]
