# Generated by Django 4.1.7 on 2023-02-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_article_description_article_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
