# Generated by Django 4.1.7 on 2023-02-25 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='summary',
        ),
    ]
