# Generated by Django 4.1.7 on 2023-02-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_title_comment_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='title',
        ),
    ]
