# Generated by Django 4.1.7 on 2023-02-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_article_comment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='article',
        ),
    ]
