# Generated by Django 4.1.7 on 2023-02-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_title_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('Thought', 'Thought'), ('Story', 'Story')], default='Story', max_length=7),
            preserve_default=False,
        ),
    ]
