# Generated by Django 4.2 on 2023-06-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_article_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="type",
            field=models.CharField(
                choices=[("Article", "Article"), ("Story", "Story")], max_length=7
            ),
        ),
    ]
